### ISSUE TITLE
windows builds cannot be tested

### ISSUE THREAD

**Issue by mattip** [scientific-python/devpy#32]
meson builds into ` build-install\usr\Lib\site-packages` on windows: for instance the numpy build ends up in ` build-install\usr\Lib\site-packages\numpy`. Even if specifying `--build-dir`, the code wants a `pythonX.Y` directory name here https://github.com/scientific-python/devpy/blob/e65f153ba3085ebdcd673ce3b6980aa0421843e9/devpy/cmds/util.py#L42 Either the meson build or this code ndeeds to change. How does it work on SciPy?

**Comment by rgommers** [comment]
It's nontrivial code in SciPy, you don't want to reinvent that particular wheel: https://github.com/scipy/scipy/blob/a145242132e6f308f5dabdb9c2e030fdc0702ade/dev.py#L281-L336

**Comment by mattip** [comment]
Did something change? On the numpy/meson branch, I can now run
```cmd
> python dev.py build
REM ninja errors out and prints a message to use this to build
> D:\temp\venv3\Scripts\meson compile -C build
REM but then this fails differently
> python dev.py test
```

Now it finds the numpy installation, but ...
I am running all this in a venv, which on windows uses a launcher python.exe to call the original python.exe. The test run invocation uses the original environment, not the venv one. So I have installed all the test dependencies into the venv, but they are ignored and the original python.exe, without the test dependencies runs. Is this a dev.py problem or a meson one?

**Comment by stefanv** [comment]
You can take a look at what it runs:

```
$ export PYTHONPATH="[...]/build-install/usr/lib64/python3.10/site-packages"
$ cd [...]/build-install/usr/lib64/python3.10/site-packages
$ python -m pytest --rootdir=[...]/build-install/usr/lib64/python3.10/site-packages pkg_name
```

Is there a reason that would fail on Windows?

I'm adding tests for Windows now.

**Comment by stefanv** [comment]
With tests for Windows passing, I will close this and we can open specific issues as they arise.

**Comment by mattip** [comment]
Sounds good
