### ISSUE TITLE
Installing devpy

### ISSUE THREAD

**Issue by astrofrog** [scientific-python/devpy#46]
Would it be possible to add installation instructions to the README? Currently doing ``pip install devpy`` appears to install an unrelated package, so even if this tool is not yet on PyPI it would be worth telling people to not install devpy from PyPI?

**Comment by stefanv** [comment]
That's a good point; we're in the process of obtaining that package (the owner said they're willing to hand it over, but communication has been slow).  In the mean time, I will update the README as you suggest.

**Comment by stefanv** [comment]
@astrofrog the package os being renamed to spin, since we could not get the PyPi name. We're making a new release, probably tomorrow.
