### ISSUE TITLE
Is `--reconfigure` necessary on each invocation of `meson setup`?

### ISSUE THREAD

**Issue by stefanv** [scientific-python/devpy#54]

**Comment by rgommers** [comment]
It's not necessary - and fairly annoying indeed. Rebuilds when nothing changed should be a no-op.

This does the right thing: https://github.com/scipy/scipy/blob/ad48d95e935c64f6b5b741543e199e32c7aacfef/dev.py#L449-L462

**Comment by stefanv** [comment]
That seems to run `--reconfigure` when the install prefix changes. That's one condition, but certainly not *all* conditions, under which that needs to happen?

**Comment by rgommers** [comment]
It should be I think. For other scenarios I can think of, like you upgraded your dev env and your compilers changed, you should already get a sensible error with reconfiguring. And Meson by design does not work with environment variables, which removes the number one source of issues.
